const randomfinger = {
  acc_id: "1",
  number: "0",
  id: "k11eg1jx",
  login_user: "",
  password: "",
  fakey: "",
  ip: "2407:d000:704:f61e:a978:23c3:984d:ea94",
  batch_id: "0",
  login_user_comment: "",
  login_cookie: "",
  cookie_updated_time: "0",
  unique_id: "",
  ip_country: "pk",
  ip_region: "punjab",
  ip_city: "sargodha",
  openfb_tab: [],
  openfb_bookmarks: "",
  fbcc_user_time_collection:
    '{"bookmark_updated_time":"0","last_close_time":1751892484}',
  password_list: "",
  password_list_updated_time: "0",
  domain_name: "newtab",
  browser_cache: "",
  name: "fadsf",
  ipchecker: "ip2location",
  sys_app_cate_id: "0",
  fbcc_proxy_acc_id: "0",
  fingerprint_config: {
    client_hints: {
      model: "",
      wow64: "",
      mobile: "",
      bitness: "64",
      platform: "Windows",
      architecture: "x86",
      platform_version: "10.0.0",
    },
    fonts: "all",
    canvas: "0",
    webgl: "2",
    audio: "1",
    webrtc: "disabled",
    gpu: "0",
    tls: "",
    page_language: "native",
    allow_scan_ports: "",
    screen_resolution: "none",
    automatic_timezone: "1",
    media_devices: "1",
    client_rects: "1",
    webgl_config: {
      unmasked_vendor: "Google Inc. (Intel)",
      unmasked_renderer:
        "ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.7262)",
      system: "Windows",
      webgpu: {
        webgpu_switch: "1",
        gpu_adapterinfo_vendor: "intel",
        gpu_adapterinfo_architecture: "gen-12lp",
      },
    },
    webgl_image: "0",
    do_not_track: "default",
    hardware_concurrency: "10",
    device_memory: "8",
    tls_switch: "0",
    scan_port_type: "1",
    device_name_switch: "2",
    device_name: "DESKTOP-W4GDJP4",
    speech_switch: "1",
    audio_id: "609",
    client_rects_id: "-4060",
    dpr: "2",
    flash: "block",
    location: "ask",
    accuracy: "1000",
    browser: "chrome",
    location_switch: "1",
    language_switch: "1",
    page_language_switch: "1",
    language: "en-US,en",
    ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.7103.114 Safari/537.36",
    browser_kernel_config: { version: "137", type: "chrome" },
    sys_resolution: "540_960",
    sys_dpr: "2",
    mac_address_config: { model: "2", address: "E4-FA-FD-06-94-75" },
    platform: "Win32",
    timezone: "",
    longitude: "72.671100",
    latitude: "32.083600",
    media_devices_num: {
      audioinput_num: "1",
      videoinput_num: "1",
      audiooutput_num: "1",
    },
    random_ua: { ua_browser: "", ua_version: "", ua_system_version: "" },
    system: "Windows",
    canvas_id: "3935",
    webgl_image_id: "2432",
    media_devices_config: [
      {
        kind: "audioinput",
        label: "Microphone Array (Conexant SmartAudio HD)",
      },
      { kind: "videoinput", label: "Integrated Camera (01d0:77fe)" },
      { kind: "audiooutput", label: "Speaker (Conexant SmartAudio HD)" },
    ],
    use_sys_resolution: "1",
    automation_controlled: "1",
    speech_voices: [
      {
        name: "Microsoft Ubax - Somali (Somalia)",
        lang: "so-SO",
        default: "0",
        localService: "1",
      },
      {
        name: "Microsoft Uzma - Urdu (Pakistan)",
        lang: "ur-PK",
        default: "0",
        localService: "1",
      },
      {
        name: "Microsoft Viktoria - Slovak (Slovakia)",
        lang: "sk-SK",
        default: "0",
        localService: "1",
      },
      {
        name: "Google Bahasa Indonesia",
        lang: "id-ID",
        default: "0",
        localService: "0",
      },
      {
        name: "Google Deutsch",
        lang: "de-DE",
        default: "0",
        localService: "0",
      },
      {
        name: "Google español",
        lang: "es-ES",
        default: "0",
        localService: "0",
      },
      {
        name: "Google español de Estados Unidos",
        lang: "es-US",
        default: "0",
        localService: "0",
      },
      {
        name: "Google français",
        lang: "fr-FR",
        default: "0",
        localService: "0",
      },
      {
        name: "Google italiano",
        lang: "it-IT",
        default: "0",
        localService: "0",
      },
      {
        name: "Google Nederlands",
        lang: "nl-NL",
        default: "0",
        localService: "0",
      },
      { name: "Google polski", lang: "pl-PL", default: "0", localService: "0" },
      {
        name: "Google português do Brasil",
        lang: "pt-BR",
        default: "0",
        localService: "0",
      },
      {
        name: "Google UK English Female",
        lang: "en-GB",
        default: "0",
        localService: "0",
      },
      {
        name: "Google UK English Male",
        lang: "en-GB",
        default: "0",
        localService: "0",
      },
      {
        name: "Google US English",
        lang: "en-US",
        default: "0",
        localService: "0",
      },
      {
        name: "Google русский",
        lang: "ru-RU",
        default: "0",
        localService: "0",
      },
      { name: "Google हिन्दी", lang: "hi-IN", default: "0", localService: "0" },
      {
        name: "Google 國語（臺灣）",
        lang: "zh-TW",
        default: "0",
        localService: "0",
      },
      { name: "Google 日本語", lang: "ja-JP", default: "0", localService: "0" },
      { name: "Google 한국의", lang: "ko-KR", default: "0", localService: "0" },
      {
        name: "Google 普通话（中国大陆）",
        lang: "zh-CN",
        default: "0",
        localService: "0",
      },
      {
        name: "Google 粤語（香港）",
        lang: "zh-HK",
        default: "0",
        localService: "0",
      },
    ],
    ip_timezone: "Asia/Karachi",
  },
  created_time: "2025-07-07 17:47:17",
  proxy_soft: "no_proxy",
  switch_random_finger: "0",
  fbcc_user_tag: [],
  browser_kernel_config: { version: "137", type: "chrome" },
  browser_run_args:
    "--fake-variations-channel=stable\n--variations-server-url=https://clientservices.googleapis.com/chrome-variations/seed",
  storage_strategy: "1",
  storage_cloud_option: {
    sync_history: "0",
    openfb_cookie: "0",
    sync_password: "0",
    openfb_bookmarks: "0",
    sync_localstorage_cache: "0",
    sync_indexeddb_cache: "0",
    sync_extension_cache: "0",
  },
  ip_scan_global_config: "0",
  automatic_timezone: "1",
  ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.7103.114 Safari/537.36",
  language: "en-US,en",
  page_language: "native",
  screen_resolution: "none",
  fonts: "all",
  canvas: "0",
  platform: "Win32",
  timezone: "",
  browser: "chrome",
  webgl: "2",
  audio: "1",
  webrtc: "disabled",
  webgl_image: "0",
  dpr: "2",
  flash: "block",
  scan_port_type: "1",
  allow_scan_ports: "",
  location: "ask",
  location_switch: "1",
  longitude: "72.671100",
  latitude: "32.083600",
  accuracy: "1000",
  media_devices: "1",
  media_devices_num: {
    audioinput_num: "1",
    videoinput_num: "1",
    audiooutput_num: "1",
  },
  do_not_track: "default",
  hardware_concurrency: "10",
  device_memory: "8",
  language_switch: "1",
  page_language_switch: "1",
  client_rects: "1",
  device_name_switch: "2",
  device_name: "DESKTOP-W4GDJP4",
  webgl_config: {
    unmasked_vendor: "Google Inc. (Intel)",
    unmasked_renderer:
      "ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.7262)",
    system: "Windows",
    webgpu: {
      webgpu_switch: "1",
      gpu_adapterinfo_vendor: "intel",
      gpu_adapterinfo_architecture: "gen-12lp",
    },
  },
  random_ua: { ua_browser: "", ua_version: "", ua_system_version: "" },
  speech_switch: "1",
  mac_address_config: { model: "2", address: "E4-FA-FD-06-94-75" },
  gpu: "0",
  tls: "",
  tls_switch: "0",
  client_hints: {
    model: "",
    wow64: "",
    mobile: "",
    bitness: "64",
    platform: "Windows",
    architecture: "x86",
    platform_version: "10.0.0",
  },
  batch_name: "Ungrouped",
  open_email: "",
  audio_id: "609",
  client_rects_id: "-4060",
  sys_resolution: "540_960",
  sys_dpr: "2",
  system: "Windows",
  canvas_id: "3935",
  webgl_image_id: "2432",
  media_devices_config: [
    { kind: "audioinput", label: "Microphone Array (Conexant SmartAudio HD)" },
    { kind: "videoinput", label: "Integrated Camera (01d0:77fe)" },
    { kind: "audiooutput", label: "Speaker (Conexant SmartAudio HD)" },
  ],
  use_sys_resolution: "1",
  automation_controlled: "1",
  speech_voices: [
    {
      name: "Microsoft Ubax - Somali (Somalia)",
      lang: "so-SO",
      default: "0",
      localService: "1",
    },
    {
      name: "Microsoft Uzma - Urdu (Pakistan)",
      lang: "ur-PK",
      default: "0",
      localService: "1",
    },
    {
      name: "Microsoft Viktoria - Slovak (Slovakia)",
      lang: "sk-SK",
      default: "0",
      localService: "1",
    },
    {
      name: "Google Bahasa Indonesia",
      lang: "id-ID",
      default: "0",
      localService: "0",
    },
    { name: "Google Deutsch", lang: "de-DE", default: "0", localService: "0" },
    { name: "Google español", lang: "es-ES", default: "0", localService: "0" },
    {
      name: "Google español de Estados Unidos",
      lang: "es-US",
      default: "0",
      localService: "0",
    },
    { name: "Google français", lang: "fr-FR", default: "0", localService: "0" },
    { name: "Google italiano", lang: "it-IT", default: "0", localService: "0" },
    {
      name: "Google Nederlands",
      lang: "nl-NL",
      default: "0",
      localService: "0",
    },
    { name: "Google polski", lang: "pl-PL", default: "0", localService: "0" },
    {
      name: "Google português do Brasil",
      lang: "pt-BR",
      default: "0",
      localService: "0",
    },
    {
      name: "Google UK English Female",
      lang: "en-GB",
      default: "0",
      localService: "0",
    },
    {
      name: "Google UK English Male",
      lang: "en-GB",
      default: "0",
      localService: "0",
    },
    {
      name: "Google US English",
      lang: "en-US",
      default: "0",
      localService: "0",
    },
    { name: "Google русский", lang: "ru-RU", default: "0", localService: "0" },
    { name: "Google हिन्दी", lang: "hi-IN", default: "0", localService: "0" },
    {
      name: "Google 國語（臺灣）",
      lang: "zh-TW",
      default: "0",
      localService: "0",
    },
    { name: "Google 日本語", lang: "ja-JP", default: "0", localService: "0" },
    { name: "Google 한국의", lang: "ko-KR", default: "0", localService: "0" },
    {
      name: "Google 普通话（中国大陆）",
      lang: "zh-CN",
      default: "0",
      localService: "0",
    },
    {
      name: "Google 粤語（香港）",
      lang: "zh-HK",
      default: "0",
      localService: "0",
    },
  ],
  proxy_config: {
    proxy_soft: "no_proxy",
    proxy_type: "",
    proxy_host: "",
    proxy_port: "",
    proxy_user: "",
    proxy_password: "",
  },
  sys_user_id: "7437082",
  is_free_company: "1",
  invite_code: "h1ogi1o",
  company_id: "6330665",
  os_config: { minMem: 0.1, minRatioMem: 0.02 },
  ad_space_list: [],
  env: "adsPowerNewGlobal",
  bookmark_updated_time: "0",
  domain_https: "0",
  ban_dev_tools: "0",
  lang: "en-US",
  is_open_tab: "1",
  disable_image: "0",
  image_size: "10",
  disable_video: "0",
  del_slow_storage_switch: "0",
  del_slow_storage_content: "",
  ip_auto_proxy: "country",
  auto_proxy: "country,region,city,asn,lastIp",
  is_cache: "1",
  is_openfb_cookie: "1",
  is_openfb_bookmarks: "0",
  sync_localstorage_cache: "0",
  sync_indexeddb_cache: "0",
  sync_extension_cache: "0",
  sync_history: "0",
  sync_password: "0",
  is_luminati_session: "0",
  is_fb_network_acceleration: "0",
  custom_icon: "acc_id",
  platform_protocol: "chrome",
  bg_color: "#5e7d7d",
  browser_head: "1",
  custom_icon_config: {
    type: "acc_id",
    content: "1",
    position: "",
    text_only: "0",
  },
  ignore_agent_config: "",
  blacklist: "",
  whitelist: "",
  whitelist_open:
    '["adspower.net","adspower.com","browserscan.net","loginkits.com","xmp.one"]',
  open_google_api: "0",
  browser_security_lock: "1",
  translate_webpages: "1",
  login_token: "2bea7a2d9ac6d39aa1c52ac4cde7466b",
  ip_scan_channel: "ip2location",
  hidden_notification: "0",
  disable_console: "1",
  timezone_geolocation: "0",
  disable_save_password: "0",
  not_sync_cache_not_open: "0",
  app_ids: [],
  tabAssistantExt: "0",
  optimize_launch: "1",
  sync_browser_cache: "0",
  not_find_proxy_not_open: "0",
  not_match_country_not_open: "0",
  is_check_proxy_before: "1",
  is_to_get: "0",
  open_startup_page: true,
  new_startup_page: "https://start.adspower.net/",
  open_check: "1",
  a: "44a1ec003c676a38a4bc09fdd7dcfbae",
  b: "YDwOpwbppuOjGKC/Bfw63jLh/dxMnzFw9dsvBLnTJXgQVru6WgB+35UK4crBlyTB",
  ip_timezone: "Asia/Karachi",
  get_proxy_v3: "1",
};
module.exports = randomfinger;
