const randomfinger = {
  acc_id: "2",
  number: "0",
  id: "k11ei7mx",
  login_user: "",
  password: "",
  fakey: "",
  ip: "",
  batch_id: "0",
  login_user_comment: "",
  login_cookie: "",
  cookie_updated_time: "0",
  unique_id: "",
  ip_country: "",
  ip_region: "",
  ip_city: "",
  openfb_tab: [],
  openfb_bookmarks: "",
  fbcc_user_time_collection: '{"bookmark_updated_time":"0"}',
  password_list: "",
  password_list_updated_time: "0",
  domain_name: "newtab",
  browser_cache: "",
  name: "test",
  ipchecker: "ip2location",
  sys_app_cate_id: "0",
  fbcc_proxy_acc_id: "0",
  fingerprint_config: {
    client_hints: {
      model: "",
      wow64: "",
      mobile: "",
      bitness: "64",
      platform: "Windows",
      architecture: "x86",
      platform_version: "10.0.0",
    },
    fonts: "all",
    canvas: "0",
    webgl: "2",
    audio: "1",
    webrtc: "disabled",
    gpu: "0",
    tls: "",
    page_language: "native",
    allow_scan_ports: "",
    screen_resolution: "none",
    automatic_timezone: "1",
    media_devices: "1",
    client_rects: "1",
    webgl_config: {
      unmasked_vendor: "Google Inc. (AMD)",
      unmasked_renderer:
        "ANGLE (AMD, AMD Radeon R9 M370X Direct3D11 vs_5_0 ps_5_0, D3D11)",
      system: "Windows",
      webgpu: {
        webgpu_switch: "1",
        gpu_adapterinfo_vendor: "amd",
        gpu_adapterinfo_architecture: "gcn-5",
      },
    },
    webgl_image: "0",
    do_not_track: "default",
    hardware_concurrency: "20",
    device_memory: "8",
    tls_switch: "0",
    scan_port_type: "1",
    device_name_switch: "2",
    device_name: "DESKTOP-UUMNUNU",
    speech_switch: "1",
    audio_id: "-934",
    client_rects_id: "942",
    dpr: "2",
    flash: "block",
    location: "ask",
    accuracy: "1000",
    browser: "chrome",
    location_switch: "1",
    language_switch: "1",
    page_language_switch: "1",
    language: "en-US,en",
    ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.7103.113 Safari/537.36",
    browser_kernel_config: { version: "137", type: "chrome" },
    sys_resolution: "540_960",
    sys_dpr: "2",
    mac_address_config: { model: "2", address: "E8-2A-EA-F5-32-09" },
    platform: "Win32",
    timezone: "",
    longitude: "",
    latitude: "",
    media_devices_num: {
      audioinput_num: "1",
      videoinput_num: "1",
      audiooutput_num: "1",
    },
    random_ua: { ua_browser: "", ua_version: "", ua_system_version: "" },
    system: "Windows",
    canvas_id: "8616",
    webgl_image_id: "9999",
    media_devices_config: [
      {
        kind: "audioinput",
        label: "Microphone Array (2- Conexant SmartAudio HD)",
      },
      { kind: "videoinput", label: "Integrated Camera (baf8:5cde)" },
      { kind: "audiooutput", label: "Speaker (2- Conexant SmartAudio HD)" },
    ],
    use_sys_resolution: "1",
    automation_controlled: "1",
    speech_voices: [
      {
        name: "Microsoft Salome - Spanish (Colombia)",
        lang: "es-CO",
        default: "0",
        localService: "1",
      },
      {
        name: "Microsoft Sapna - Kannada (India)",
        lang: "kn-IN",
        default: "0",
        localService: "1",
      },
      {
        name: "Microsoft Shruti - Telugu (India)",
        lang: "te-IN",
        default: "0",
        localService: "1",
      },
      {
        name: "Google Bahasa Indonesia",
        lang: "id-ID",
        default: "0",
        localService: "0",
      },
      {
        name: "Google Deutsch",
        lang: "de-DE",
        default: "0",
        localService: "0",
      },
      {
        name: "Google español",
        lang: "es-ES",
        default: "0",
        localService: "0",
      },
      {
        name: "Google español de Estados Unidos",
        lang: "es-US",
        default: "0",
        localService: "0",
      },
      {
        name: "Google français",
        lang: "fr-FR",
        default: "0",
        localService: "0",
      },
      {
        name: "Google italiano",
        lang: "it-IT",
        default: "0",
        localService: "0",
      },
      {
        name: "Google Nederlands",
        lang: "nl-NL",
        default: "0",
        localService: "0",
      },
      { name: "Google polski", lang: "pl-PL", default: "0", localService: "0" },
      {
        name: "Google português do Brasil",
        lang: "pt-BR",
        default: "0",
        localService: "0",
      },
      {
        name: "Google UK English Female",
        lang: "en-GB",
        default: "0",
        localService: "0",
      },
      {
        name: "Google UK English Male",
        lang: "en-GB",
        default: "0",
        localService: "0",
      },
      {
        name: "Google US English",
        lang: "en-US",
        default: "0",
        localService: "0",
      },
      {
        name: "Google русский",
        lang: "ru-RU",
        default: "0",
        localService: "0",
      },
      { name: "Google हिन्दी", lang: "hi-IN", default: "0", localService: "0" },
      {
        name: "Google 國語（臺灣）",
        lang: "zh-TW",
        default: "0",
        localService: "0",
      },
      { name: "Google 日本語", lang: "ja-JP", default: "0", localService: "0" },
      { name: "Google 한국의", lang: "ko-KR", default: "0", localService: "0" },
      {
        name: "Google 普通话（中国大陆）",
        lang: "zh-CN",
        default: "0",
        localService: "0",
      },
      {
        name: "Google 粤語（香港）",
        lang: "zh-HK",
        default: "0",
        localService: "0",
      },
    ],
  },
  created_time: "2025-07-07 18:33:50",
  proxy_soft: "other",
  switch_random_finger: "0",
  fbcc_user_tag: [],
  browser_kernel_config: { version: "137", type: "chrome" },
  browser_run_args:
    "--fake-variations-channel=stable\n--variations-server-url=https://clientservices.googleapis.com/chrome-variations/seed",
  storage_strategy: "1",
  storage_cloud_option: {
    sync_history: "0",
    openfb_cookie: "0",
    sync_password: "0",
    openfb_bookmarks: "0",
    sync_localstorage_cache: "0",
    sync_indexeddb_cache: "0",
    sync_extension_cache: "0",
  },
  ip_scan_global_config: "0",
  automatic_timezone: "1",
  ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.7103.113 Safari/537.36",
  language: "en-US,en",
  page_language: "native",
  screen_resolution: "none",
  fonts: "all",
  canvas: "0",
  platform: "Win32",
  timezone: "",
  browser: "chrome",
  webgl: "2",
  audio: "1",
  webrtc: "disabled",
  webgl_image: "0",
  dpr: "2",
  flash: "block",
  scan_port_type: "1",
  allow_scan_ports: "",
  location: "ask",
  location_switch: "1",
  longitude: "",
  latitude: "",
  accuracy: "1000",
  media_devices: "1",
  media_devices_num: {
    audioinput_num: "1",
    videoinput_num: "1",
    audiooutput_num: "1",
  },
  do_not_track: "default",
  hardware_concurrency: "20",
  device_memory: "8",
  language_switch: "1",
  page_language_switch: "1",
  client_rects: "1",
  device_name_switch: "2",
  device_name: "DESKTOP-UUMNUNU",
  webgl_config: {
    unmasked_vendor: "Google Inc. (AMD)",
    unmasked_renderer:
      "ANGLE (AMD, AMD Radeon R9 M370X Direct3D11 vs_5_0 ps_5_0, D3D11)",
    system: "Windows",
    webgpu: {
      webgpu_switch: "1",
      gpu_adapterinfo_vendor: "amd",
      gpu_adapterinfo_architecture: "gcn-5",
    },
  },
  random_ua: { ua_browser: "", ua_version: "", ua_system_version: "" },
  speech_switch: "1",
  mac_address_config: { model: "2", address: "E8-2A-EA-F5-32-09" },
  gpu: "0",
  tls: "",
  tls_switch: "0",
  client_hints: {
    model: "",
    wow64: "",
    mobile: "",
    bitness: "64",
    platform: "Windows",
    architecture: "x86",
    platform_version: "10.0.0",
  },
  batch_name: "Ungrouped",
  open_email: "",
  audio_id: "-934",
  client_rects_id: "942",
  sys_resolution: "540_960",
  sys_dpr: "2",
  system: "Windows",
  canvas_id: "8616",
  webgl_image_id: "9999",
  media_devices_config: [
    {
      kind: "audioinput",
      label: "Microphone Array (2- Conexant SmartAudio HD)",
    },
    { kind: "videoinput", label: "Integrated Camera (baf8:5cde)" },
    { kind: "audiooutput", label: "Speaker (2- Conexant SmartAudio HD)" },
  ],
  use_sys_resolution: "1",
  automation_controlled: "1",
  speech_voices: [
    {
      name: "Microsoft Salome - Spanish (Colombia)",
      lang: "es-CO",
      default: "0",
      localService: "1",
    },
    {
      name: "Microsoft Sapna - Kannada (India)",
      lang: "kn-IN",
      default: "0",
      localService: "1",
    },
    {
      name: "Microsoft Shruti - Telugu (India)",
      lang: "te-IN",
      default: "0",
      localService: "1",
    },
    {
      name: "Google Bahasa Indonesia",
      lang: "id-ID",
      default: "0",
      localService: "0",
    },
    { name: "Google Deutsch", lang: "de-DE", default: "0", localService: "0" },
    { name: "Google español", lang: "es-ES", default: "0", localService: "0" },
    {
      name: "Google español de Estados Unidos",
      lang: "es-US",
      default: "0",
      localService: "0",
    },
    { name: "Google français", lang: "fr-FR", default: "0", localService: "0" },
    { name: "Google italiano", lang: "it-IT", default: "0", localService: "0" },
    {
      name: "Google Nederlands",
      lang: "nl-NL",
      default: "0",
      localService: "0",
    },
    { name: "Google polski", lang: "pl-PL", default: "0", localService: "0" },
    {
      name: "Google português do Brasil",
      lang: "pt-BR",
      default: "0",
      localService: "0",
    },
    {
      name: "Google UK English Female",
      lang: "en-GB",
      default: "0",
      localService: "0",
    },
    {
      name: "Google UK English Male",
      lang: "en-GB",
      default: "0",
      localService: "0",
    },
    {
      name: "Google US English",
      lang: "en-US",
      default: "0",
      localService: "0",
    },
    { name: "Google русский", lang: "ru-RU", default: "0", localService: "0" },
    { name: "Google हिन्दी", lang: "hi-IN", default: "0", localService: "0" },
    {
      name: "Google 國語（臺灣）",
      lang: "zh-TW",
      default: "0",
      localService: "0",
    },
    { name: "Google 日本語", lang: "ja-JP", default: "0", localService: "0" },
    { name: "Google 한국의", lang: "ko-KR", default: "0", localService: "0" },
    {
      name: "Google 普通话（中国大陆）",
      lang: "zh-CN",
      default: "0",
      localService: "0",
    },
    {
      name: "Google 粤語（香港）",
      lang: "zh-HK",
      default: "0",
      localService: "0",
    },
  ],
  proxy_config: {
    proxy_soft: "other",
    proxy_type: "http",
    proxy_url: "",
    proxy_host: "b2b-s10.liveproxies.io",
    proxy_port: "7383",
    proxy_user: "LV88332086-lv_us-235255",
    proxy_password: "ysieJMfkA40xZRdPzFXe",
  },
  sys_user_id: "7437082",
  is_free_company: "1",
  invite_code: "h1ogi1o",
  company_id: "6330665",
  os_config: { minMem: 0.1, minRatioMem: 0.02 },
  ad_space_list: [],
  env: "adsPowerNewGlobal",
  bookmark_updated_time: "0",
  domain_https: "0",
  ban_dev_tools: "0",
  lang: "en-US",
  is_open_tab: "1",
  disable_image: "0",
  image_size: "10",
  disable_video: "0",
  del_slow_storage_switch: "0",
  del_slow_storage_content: "",
  ip_auto_proxy: "country",
  auto_proxy: "country,region,city,asn,lastIp",
  is_cache: "1",
  is_openfb_cookie: "1",
  is_openfb_bookmarks: "0",
  sync_localstorage_cache: "0",
  sync_indexeddb_cache: "0",
  sync_extension_cache: "0",
  sync_history: "0",
  sync_password: "0",
  is_luminati_session: "0",
  is_fb_network_acceleration: "0",
  custom_icon: "acc_id",
  platform_protocol: "chrome",
  bg_color: "#007d7d",
  browser_head: "2",
  custom_icon_config: {
    type: "acc_id",
    content: "2",
    position: "",
    text_only: "0",
  },
  ignore_agent_config: "",
  blacklist: "",
  whitelist: "",
  whitelist_open:
    '["adspower.net","adspower.com","browserscan.net","loginkits.com","xmp.one"]',
  open_google_api: "0",
  browser_security_lock: "1",
  translate_webpages: "1",
  login_token: "2bea7a2d9ac6d39aa1c52ac4cde7466b",
  ip_scan_channel: "ip2location",
  hidden_notification: "0",
  disable_console: "1",
  timezone_geolocation: "0",
  disable_save_password: "0",
  not_sync_cache_not_open: "0",
  app_ids: [],
  tabAssistantExt: "0",
  optimize_launch: "1",
  sync_browser_cache: "0",
  not_find_proxy_not_open: "0",
  not_match_country_not_open: "0",
  is_check_proxy_before: "1",
  is_to_get: "0",
  open_startup_page: true,
  new_startup_page: "https://start.adspower.net/",
  open_check: "1",
  a: "4904b96b467060f655b8eb4d1a23535f",
  b: "KAQlYlQgpRfZyihRttC7TFWURlbcawgUy6cQCPaooHofkJREwFhSaXOqP4WnYBTE",
};
module.exports = randomfinger;
